### 넘파이 임포트

In [1]:
import numpy as np 

### 생성 함수

In [9]:
li = [1, 2, 3, 4, 5]
print(type(li))
arr = np.array(li) # ndarray 로 변환 
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


####  np.arange()

파이썬 range 함수와 같지만 ndarray 객체를 생성한다. 

In [11]:
np.arange(1, 6)

array([1, 2, 3, 4, 5])

####  np.zeros(), np.ones(), np.full()

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
arr = np.zeros( (2, 3) ) 

In [20]:
arr.shape

(2, 3)

In [21]:
arr = np.zeros( (2, 2, 2) ) 

In [22]:
arr.shape

(2, 2, 2)

In [23]:
arr = np.ones( (2, 2, 2) ) 

In [24]:
arr

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [27]:
arr = np.full( (2, 2, 2) , 7 )
arr

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

항등 형렬

In [28]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 형상 관련 함수

In [29]:
arr = np.arange(1,6)

In [30]:
arr.shape

(5,)

In [31]:
len(arr)

5

np.reshape 함수

In [44]:
arr = np.arange(1,7)
arr

array([1, 2, 3, 4, 5, 6])

In [45]:
arr = np.reshape(arr, (2,3))

In [46]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
arr[1,1]

5

In [51]:
arr[1][1]

5

In [52]:
arr[1]

array([4, 5, 6])

In [53]:
arr[1][1]

5

In [54]:
arr = np.reshape(arr, (3,2))

In [55]:
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

####  -1은 그 행이나 열은 그대로 두고라는 뜻 

In [56]:
arr = np.reshape(arr, (-1,3))
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
arr = np.reshape(arr, (3,-1))
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

#### 행벡터를 열벡터로 바꾼다.

In [60]:
arr = np.arange(1,7)
arr.shape

(6,)

In [61]:
arr = np.reshape( arr, (-1,1) )
arr.shape

(6, 1)

###  행렬의 전치 

In [62]:
arr = np.arange(1,7)
arr = np.reshape( arr, (-1,3) )
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [65]:
np.reshape( arr, (-1,2) )

array([[1, 2],
       [3, 4],
       [5, 6]])

In [66]:
arr = np.arange(1,7)
arr

array([1, 2, 3, 4, 5, 6])

In [67]:
arr.T

array([1, 2, 3, 4, 5, 6])

In [68]:
np.reshape( arr, (-1,1) )

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

### 난수 발생 함수

In [163]:
np.random.randint(1,10)

4

In [184]:
np.random.randint(1, 10, 5)

array([3, 8, 6, 1, 8])

평균은 0에 수렴하고 표준 편차는 1에 수렴하는 랜덤 수 생성( 가우시안 정규분포 )

In [281]:
arr = np.random.randn(1000000)
np.mean(arr)

-0.0004812032279231797

In [307]:
arr = np.random.randn(1000000)
np.std(arr)

1.000623108056724

랜덤 seed  지정하기 

In [308]:
np.random.seed(42)

### 넘파이 연산 함수

In [310]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = a+b
c

array([5, 7, 9])

#### 넘파이 배열의 브로드캐스트 연산

In [311]:
a = np.array([1,2,3])
b = 10
c = a+b
c

array([11, 12, 13])

In [313]:
a = np.array([[1,2],[3,4]])
b = np.array([10,20])
c = a+b
c

array([[11, 22],
       [13, 24]])

### 넘파이 Array의 인덱싱

In [2]:
import numpy as np
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr1[0]

0

In [4]:
type(arr1[0])

numpy.int32

In [5]:
arr1[3]

3

In [6]:
arr1[3:9]

array([3, 4, 5, 6, 7, 8])

In [7]:
type(arr1[3:9])

numpy.ndarray

In [8]:
arr1[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr1[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [11]:
arr1[:3]

array([0, 1, 2])

In [12]:
arr1[-4:]

array([6, 7, 8, 9])

#### 2차원 배열의 인덱싱

In [13]:
arr2 = np.array( [[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12]])
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
arr2[0,0]

1

In [15]:
arr2[:,2]

array([ 3,  7, 11])

In [16]:
arr2[:,2].shape

(3,)

In [17]:
arr2[2, :]

array([ 9, 10, 11, 12])

In [18]:
arr2[:, 1:3 ]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [20]:
temp = [1,3]
arr2[:, temp ]

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [21]:
arr2[ [0,2] , :]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [23]:
arr2[ [0,2] , 1]

array([ 2, 10])

In [24]:
arr2[ [0,2] , 1:3]

array([[ 2,  3],
       [10, 11]])

In [25]:
arr2[ [0,2] , [1,3]]

array([ 2, 12])

In [26]:
index = np.array([0, 2])
arr2[ index , :]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

#### Array boolean 인덱싱(마스크)

In [28]:
data = np.arange(16).reshape((4,4))
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [30]:
names = np.array([ 'Kim', 'Lee', 'Park' , 'Choi'])
names

array(['Kim', 'Lee', 'Park', 'Choi'], dtype='<U4')

In [31]:
names_mask = (names == 'Lee')
names_mask

array([False,  True, False, False])

In [38]:
data[:, names_mask ]

array([[ 1],
       [ 5],
       [ 9],
       [13]])

In [39]:
data[ data[:, 0] > 4, : ]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### Numpy 함수

In [40]:
data = np.arange(16).reshape((4,4))
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [41]:
np.sqrt(data)  #  data ** 0.5

array([[0.        , 1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 3.16227766, 3.31662479],
       [3.46410162, 3.60555128, 3.74165739, 3.87298335]])

In [42]:
np.square(data)  #  data ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225]], dtype=int32)

In [43]:
np.exp(data)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04],
       [1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06]])

In [44]:
np.log(data)

C:\Users\edu\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([[      -inf, 0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509, 2.39789527],
       [2.48490665, 2.56494936, 2.63905733, 2.7080502 ]])

In [45]:
np.exp(np.log(data))

C:\Users\edu\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [46]:
np.log(np.exp(data))

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [49]:
np.sign(data)

array([[0, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [51]:
a = np.log(data)
np.isinf(a)

C:\Users\edu\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([[ True, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

#### 통계 함수

In [52]:
data = np.arange(16).reshape((4,4))
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [53]:
np.sum(data)

120

In [54]:
np.sum(data, axis=1)

array([ 6, 22, 38, 54])

In [55]:
np.sum(data, axis=0)

array([24, 28, 32, 36])

In [56]:
np.mean(data)

7.5

In [57]:
np.mean(data, axis=1)

array([ 1.5,  5.5,  9.5, 13.5])

In [58]:
np.mean(data, axis=0)

array([6., 7., 8., 9.])

In [59]:
np.max(data)

15

In [60]:
np.max(data, axis=1)

array([ 3,  7, 11, 15])

In [61]:
np.max(data, axis=0)

array([12, 13, 14, 15])

In [62]:
np.argmax(data)

15

In [63]:
np.argmax(data, axis=1)

array([3, 3, 3, 3], dtype=int64)

### 행렬 곱

In [66]:
a = np.array([1,2,3])
b = np.array([2,2,2])
np.sum(a*b)

12

In [65]:
np.dot(a, b)

12

In [67]:
a = np.array([[1,2],
              [3,4]])

b = np.array([[2,2],
              [2,2]])

In [68]:
np.sum(a*b)

20

In [69]:
np.dot(a, b)

array([[ 6,  6],
       [14, 14]])

In [80]:
a = np.array([[1,2],
              [3,4]])

b = np.array([[2,3],
              [2,3]])

In [81]:
np.dot(a, b)

array([[ 6,  9],
       [14, 21]])

In [82]:
np.dot(b, a)

array([[11, 16],
       [11, 16]])

In [73]:
a = np.array([[1,2],
              [3,4]])

b = np.array([[2,3]])

In [74]:
np.dot(a, b)

ValueError: shapes (2,2) and (1,2) not aligned: 2 (dim 1) != 1 (dim 0)

In [75]:
a = np.array([[1,2],
              [3,4]])

b = np.array([[2,3],
              [2,3],
              [2,3]])

In [76]:
np.dot(a, b)

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [77]:
a = np.array([[1,2]])

b = np.array([[2,3],
              [2,3]])

In [78]:
np.dot(a, b)

array([[6, 9]])

In [83]:
a = np.array([[1,2]])

b = np.array([[2],
              [2]])

In [84]:
np.dot(a, b)

array([[6]])

In [85]:
np.dot(b, a)

array([[2, 4],
       [2, 4]])

In [91]:
x = np.array([[1,2],[3,4],[5,6]])
# x.shape
n_features=2
units=2
w1 = np.ones((n_features, units))  
# w1.shape
# (특성 개수, 은닉층의 크기)
b1 = np.zeros(units) 
# b1.shape
z = np.dot(x,w1) + b1
z

array([[ 3.,  3.],
       [ 7.,  7.],
       [11., 11.]])

### 고차원 배열 사용법

In [96]:
x = np.array([ [[1,2],[3,4]] , [[5,6],[7,8]] ])
x.shape
len(x)

2

In [97]:
x

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [98]:
x[0]

array([[1, 2],
       [3, 4]])

In [99]:
x[1]

array([[5, 6],
       [7, 8]])

In [100]:
a = np.array([[1,2],[3,4]])
a.T

array([[1, 3],
       [2, 4]])

In [101]:
np.swapaxes(a, 0, 1)

array([[1, 3],
       [2, 4]])

In [102]:
np.swapaxes(a, 1, 0)

array([[1, 3],
       [2, 4]])

In [104]:
(x.T).shape

(2, 2, 2)

In [105]:
x.T

array([[[1, 5],
        [3, 7]],

       [[2, 6],
        [4, 8]]])

In [109]:
np.swapaxes(x, 0, 2)

array([[[1, 5],
        [3, 7]],

       [[2, 6],
        [4, 8]]])

In [110]:
np.swapaxes(x, 0, 1)

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

In [111]:
np.swapaxes(x, 1, 2)

array([[[1, 3],
        [2, 4]],

       [[5, 7],
        [6, 8]]])

In [113]:
np.sum(x, axis=2)

array([[ 3,  7],
       [11, 15]])

In [114]:
np.sum(x, axis=1)

array([[ 4,  6],
       [12, 14]])

In [115]:
np.sum(x, axis=0)

array([[ 6,  8],
       [10, 12]])

#### 4차원 배열 예제

In [116]:
x = np.array([[[[1,2],[3,4]],[[5,6],[7,8]]],[[[9,10],[11,12]],[[13,14],[15,16]]]])

In [117]:
np.sum(x, axis=3)

array([[[ 3,  7],
        [11, 15]],

       [[19, 23],
        [27, 31]]])

In [118]:
np.sum(x, axis=2)

array([[[ 4,  6],
        [12, 14]],

       [[20, 22],
        [28, 30]]])

In [119]:
np.sum(x, axis=1)

array([[[ 6,  8],
        [10, 12]],

       [[22, 24],
        [26, 28]]])

In [120]:
np.sum(x, axis=0)

array([[[10, 12],
        [14, 16]],

       [[18, 20],
        [22, 24]]])

In [121]:
np.swapaxes(x, 0, 3)

array([[[[ 1,  9],
         [ 3, 11]],

        [[ 5, 13],
         [ 7, 15]]],


       [[[ 2, 10],
         [ 4, 12]],

        [[ 6, 14],
         [ 8, 16]]]])

In [122]:
np.swapaxes(x, 1, 2)


array([[[[ 1,  2],
         [ 5,  6]],

        [[ 3,  4],
         [ 7,  8]]],


       [[[ 9, 10],
         [13, 14]],

        [[11, 12],
         [15, 16]]]])

In [124]:
x = np.array([ [ [[1],[2]], [[3],[4]] ] ])
x.shape

(1, 2, 2, 1)

In [125]:
np.swapaxes(x, 0, 2).shape

(2, 2, 1, 1)

In [126]:
np.swapaxes(x, 0, 2)

array([[[[1]],

        [[3]]],


       [[[2]],

        [[4]]]])

In [127]:
x = np.arange(36).reshape( (2,2,3,3) )

In [128]:
x

array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]],


       [[[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]],

        [[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]]]])