### 넘파이 임포트

In [1]:
import numpy as np 

### 생성 함수

In [9]:
li = [1, 2, 3, 4, 5]
print(type(li))
arr = np.array(li) # ndarray 로 변환 
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


####  np.arange()

파이썬 range 함수와 같지만 ndarray 객체를 생성한다. 

In [11]:
np.arange(1, 6)

array([1, 2, 3, 4, 5])

####  np.zeros(), np.ones(), np.full()

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
arr = np.zeros( (2, 3) ) 

In [20]:
arr.shape

(2, 3)

In [21]:
arr = np.zeros( (2, 2, 2) ) 

In [22]:
arr.shape

(2, 2, 2)

In [23]:
arr = np.ones( (2, 2, 2) ) 

In [24]:
arr

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [27]:
arr = np.full( (2, 2, 2) , 7 )
arr

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

항등 형렬

In [28]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 형상 관련 함수

In [29]:
arr = np.arange(1,6)

In [30]:
arr.shape

(5,)

In [31]:
len(arr)

5

np.reshape 함수

In [44]:
arr = np.arange(1,7)
arr

array([1, 2, 3, 4, 5, 6])

In [45]:
arr = np.reshape(arr, (2,3))

In [46]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
arr[1,1]

5

In [51]:
arr[1][1]

5

In [52]:
arr[1]

array([4, 5, 6])

In [53]:
arr[1][1]

5

In [54]:
arr = np.reshape(arr, (3,2))

In [55]:
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

####  -1은 그 행이나 열은 그대로 두고라는 뜻 

In [56]:
arr = np.reshape(arr, (-1,3))
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
arr = np.reshape(arr, (3,-1))
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

#### 행벡터를 열벡터로 바꾼다.

In [60]:
arr = np.arange(1,7)
arr.shape

(6,)

In [61]:
arr = np.reshape( arr, (-1,1) )
arr.shape

(6, 1)

###  행렬의 전치 

In [62]:
arr = np.arange(1,7)
arr = np.reshape( arr, (-1,3) )
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [65]:
np.reshape( arr, (-1,2) )

array([[1, 2],
       [3, 4],
       [5, 6]])

In [66]:
arr = np.arange(1,7)
arr

array([1, 2, 3, 4, 5, 6])

In [67]:
arr.T

array([1, 2, 3, 4, 5, 6])

In [68]:
np.reshape( arr, (-1,1) )

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

### 난수 발생 함수

In [163]:
np.random.randint(1,10)

4

In [184]:
np.random.randint(1, 10, 5)

array([3, 8, 6, 1, 8])

평균은 0에 수렴하고 표준 편차는 1에 수렴하는 랜덤 수 생성( 가우시안 정규분포 )

In [281]:
arr = np.random.randn(1000000)
np.mean(arr)

-0.0004812032279231797

In [307]:
arr = np.random.randn(1000000)
np.std(arr)

1.000623108056724

랜덤 seed  지정하기 

In [308]:
np.random.seed(42)

### 넘파이 연산 함수

In [310]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = a+b
c

array([5, 7, 9])

#### 넘파이 배열의 브로드캐스트 연산

In [311]:
a = np.array([1,2,3])
b = 10
c = a+b
c

array([11, 12, 13])

In [313]:
a = np.array([[1,2],[3,4]])
b = np.array([10,20])
c = a+b
c

array([[11, 22],
       [13, 24]])