## 넘파이 임포트

In [1]:
import numpy as np

## 생성 함수

In [6]:
li = [1, 2, 3, 4, 5]
print(type(li))
arr = np.array(li) #  ndarray로 변환
arr
print(arr) # print 사용하면 내부 데이터만 나온다
print(type(arr))
# 타입도 다르고 메모리적으로도 다르다

<class 'list'>
[1 2 3 4 5]
<class 'numpy.ndarray'>


### np.arange()

파이썬 range 함수와 같지만 ndarray 객체를 생성한다.

In [9]:
np.arange(1, 7) 
# 1~6까지 ndarray배열이 생성된다
# 리스트 없이도 이렇게 생성 가능하다


array([1, 2, 3, 4, 5, 6])

### np.zeros(), np.ones(), np.full() 

In [11]:
np.zeros(10)
# 기본적인 타입은 float형태로 초기값 0이 들어간다

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
arr = np.zeros((2,3))
# 튜플 형태로 넣어주면 2차원 배열도 만들 수 있다

In [20]:
arr.shape 
# 형상을 찍어주는 것.
# 형상은 튜플로 묶어서 넣어줘야 한다.
# 따로 낱개로 쓰면 인식하지 못한다

(2, 3)

In [23]:
arr = np.zeros((2,2,2))
arr.shape
# 3차원 행렬도 만들 수 있다
# 그림이면 4차원 동영상이면 5차원까지 쓴다 딥러닝에서는


(2, 2, 2)