## 넘파이 임포트

In [1]:
import numpy as np

## 생성 함수

In [2]:
li = [1, 2, 3, 4, 5]
print(type(li))
arr = np.array(li) #  ndarray로 변환
arr
print(arr) # print 사용하면 내부 데이터만 나온다
print(type(arr))
# 타입도 다르고 메모리적으로도 다르다

<class 'list'>
[1 2 3 4 5]
<class 'numpy.ndarray'>


### np.arange()

파이썬 range 함수와 같지만 ndarray 객체를 생성한다.

In [3]:
np.arange(1, 7) 
# 1~6까지 ndarray배열이 생성된다
# 리스트 없이도 이렇게 생성 가능하다


array([1, 2, 3, 4, 5, 6])

### np.zeros(), np.ones(), np.full() 

In [4]:
np.zeros(10)
# 기본적인 타입은 float형태로 초기값 0이 들어간다

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
arr = np.zeros((2,3))
# 튜플 형태로 넣어주면 2차원 배열도 만들 수 있다

In [6]:
arr.shape 
# 형상을 찍어주는 것.
# 형상은 튜플로 묶어서 넣어줘야 한다.
# 따로 낱개로 쓰면 인식하지 못한다

(2, 3)

In [7]:
arr = np.zeros((2,2,2))
arr.shape
# 3차원 행렬도 만들 수 있다
# 그림이면 4차원 동영상이면 5차원까지 쓴다 딥러닝에서는


(2, 2, 2)

In [8]:
arr = np.ones((2,2,2))

In [9]:
arr

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [10]:
arr = np.full((2, 2, 2), 7)

In [11]:
arr

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

### 항등 행렬 

어떤 행렬에 항등행렬을 곱하면 어떤 행렬이 그대로 나옴
대각선만 1로 채운 행렬

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 형상 관련 함수 

In [13]:
arr = np.arange(1,6)

In [14]:
arr.shape 
# 뭐 콤마로 끝나면 1차원 배열임을 알 수 있다

(5,)

In [15]:
len(arr)

5

### np.reshape 형상바꾸기 함수 

In [16]:
arr = np.arange(1,7)
arr 

array([1, 2, 3, 4, 5, 6])

<span style="color:red"><b>형상은 튜플로 넣어줘야 한다.</b> </span>

In [17]:
np.reshape(arr, (2,3)) 
# 형상은 튜플로 넣어줘야 한다. 

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
arr
# 행렬로 저장하고 싶으면
# arr = np.reshape(arr, (2,3)) 해줘야 arr이 행렬 2 3으로 바뀐걸 참조한다

array([1, 2, 3, 4, 5, 6])

In [19]:
arr = np.reshape(arr, (2,3))

In [20]:
arr[1][1]

5

In [21]:
arr[1,1]

5

In [22]:
arr = np.reshape(arr, (3,2))

In [23]:
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

### -1의 뜻은 그 행이나 열은 그대로 두고 라는 의미이다

In [24]:
arr = np.reshape(arr, (-1,3))
# 여기서 강제로 지정한 것은 열뿐이다
# 굳이 행을 지시하지 않아도 자동 2,3이 된다

In [25]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
arr = np.reshape(arr, (3,-1))

In [27]:
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

### 행벡터를 열벡터로 바꾼다 

차원이 바뀌는 문제는 reshape만 가능하다
np.shape


In [28]:
arr = np.arange(1,7)
np.shape(arr)

(6,)

In [29]:
arr = np.reshape(arr, (-1, 1))
arr
# 꺽쇠 두개인 2차원 배열로 바뀐다
# 위에 것과 형상이 변한다

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [30]:
np.shape(arr)

(6, 1)

### 행렬의 전치 

전치와 단순한 reshape은 다르다!!!! 
바뀌는 축이 달라!
#### <span style="color:red"> 행과 열이 바뀐다 </span>

In [31]:
arr = np.arange(1,7)
arr = np.reshape(arr, (-1,3))
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [33]:
np.reshape(arr, (-1,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [34]:
arr = np.arange(1,7)
arr

array([1, 2, 3, 4, 5, 6])

In [35]:
arr.T
# 1차원은 전치해도 그대로 나온다!!!!!!!!!!!!!!!!!!!!!!
# reshape만 세로로 나오게 할 수 있다 1차원에 대해서는

array([1, 2, 3, 4, 5, 6])

In [36]:
np.reshape(arr, (-1,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

### 난수 발생 함수 

In [37]:
np.random.randint(1,10)
# 앞의 1은 포함하지만 10은 제외

8

In [38]:
np.random.randint(1,10, 5)
# 마지막은 난수의 갯수를 의미한다 

array([3, 8, 8, 7, 8])

###  평균은 0에 수렴하고 표준 편차는 1에 수렴하는 랜덤 수 생성
### (가우시안 정규분포)

In [39]:
np.random.randn(5)
# 값이 정수로 덜어지는 값이 아니라 부동소수점.
# 의미없는 부동소수점이 매번 다르게 발생한다
# 범위를 가지고 있는 느낌이 있다


array([ 0.16324386,  0.53933566, -1.67481547, -1.11058234, -0.7214944 ])

In [40]:
arr = np.random.randn(5)
np.mean(arr)

0.06525376113051533

In [41]:
arr = np.random.randn(10000)
np.mean(arr)
# 평균이 0에 근접하는 난수가 0에 근접하게 발생한다.
# 범위는 어떻게 될 것인가?


0.0035284066605848325

In [42]:
arr = np.random.randn(10000)
np.std(arr)
# std는 표준편차다
# 이것을 가우시안 정규분포라고 한다
# 가우시안 정규분포로 랜덤을 만드는 것이고 
# 평균은 0에 근접, 표준편차는 1에 근접한다

0.9907348090156953

In [43]:
arr = np.random.randn(1000000)
np.mean(arr)


-0.0006685561656018076

In [44]:
arr = np.random.randn(1000000)
np.std(arr)

1.0001262849466646

### 랜덤 seed 지정하기 

In [51]:
np.random.seed(42)

### 넘파이 연산 함수 

In [46]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a+b

array([5, 7, 9])

In [47]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = a+b
c
# 이렇게 해줘야 다른데에서도 쓸 수 있다. 값이 남기 때문

array([5, 7, 9])

### 넘파이 배열의 브로드캐스트 연산 

차원이 다를 때의 연산

### <span style="color:red">차원이 적은쪽에서 고차원으로 변형이 이뤄진다(임시적으로)</span>

In [48]:
a = np.array([1,2,3])
b = 10 # scala라서 차원이 다른데 더하기가 된다. 모든 멤버가 전부!
c = a+b
c


array([11, 12, 13])

In [49]:
a = np.array([[1,2],[3,4]])
b = 10 # scala라서 차원이 다른데 더하기가 된다. 모든 멤버가 전부!
c = a+b
c


array([[11, 12],
       [13, 14]])

### <span style="color:red">차원다르고 원소 개수 달라도 저차원이 고차원쪽으로 형 변환되어 원래 값 복제되어 만들어진다</span>

In [50]:
a = np.array([[1,2],[3,4]])
b = np.array([10,20]) #이렇게도 된다!!!
c = a+b
c          
          

array([[11, 22],
       [13, 24]])

### 넘파이 Array의 인덱싱

In [53]:
arr1 = np.arange(10) # 0~9까지 10개의 인덱스가 생성됨
arr1 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
arr1[0]

0

값을 꺼내는 것은 차원이 바뀐다
슬라이싱과 값을 꺼내는 것은 다르다
꺼내온 값 자체의 타입은 int가 될 것이다.

In [55]:
type(arr1[0])

numpy.int32

In [56]:
arr1[3]

3

이것은 슬라이싱과 비교되어야 한다

In [57]:
arr1[3:9]

array([3, 4, 5, 6, 7, 8])

값을 꺼낼 때에는 int로 바뀌지만
슬라이싱은 구분배열로 꺼내는 것이기 때문에 
배열의 일부분이 추출된다.

In [59]:
type(arr1[3:9])

numpy.ndarray

슬라이싱 할 때에는 타입이 유지된다.
배열의 형상을 유지한 채 또다른 배열을 만들어주는 것으로 생각하자.

모든값을 추출하려면

In [61]:
arr1[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
arr1[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [64]:
arr1[:3]

array([0, 1, 2])

In [65]:
arr1[-4:]

array([6, 7, 8, 9])

### 2차원 배열의 인덱싱에 대해

3행 4열짜리 행렬 만든다
2차원 배열

In [66]:
arr2 = np.array( [[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12]])
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

형상을 나타내준다

In [67]:
arr2.shape

(3, 4)

2차원 배열임을 나타낸다

In [68]:
arr2.ndim

2

In [69]:
arr2[0,0]

1

행으로도 열로도 접근해서 값을 추출해낸 것이기 때문에 2차원에서 2번 추출한것과 같은 것이고 1이라는 값이 나온다.
정확히 2번 추출한 것으로 볼 수 있다.
인덱스 추출로도 볼 수 있고 값의 추출로도 볼 수 있다

In [70]:
arr2[:,2]

array([ 3,  7, 11])

이것의 의미는 무엇인가?
잘 보면 ,앞은 행을 의미하고 : 이기 때문에 모든 것을 의미하고
2라는 것은 2열을 의미한다
" 모든 행의 2열만 " 
3, 7, 11이 뽑히는 것 까지는 알겠지만
이렇게 뽑았다고 해서 (3,1) 인 2차원으로 출력되는 것은 아니다 
엄밀히 보면 이것은 값을 추출한 것이기 때문에
형상이 유지될 수 없다. 추출하면 차원이 줄어든다
세로로 뽑았다고 하더라도 2차원으로 출력되는 것이 아니라
1차원으로 출력된다. (3, ) 으로 출력된다.
열을 뽑아서 행으로 출력되는 식. 
뽑은건 행 열 2차원인데
출력되는 것은 1차원 형상으로 나온다

특정한 열이나 행을 출력할 때 많이 사용한다

In [71]:
arr2[:,2].shape

(3,)

In [73]:
arr2[2,:]

array([ 9, 10, 11, 12])

2행으로 고정하고 모든 열을 추출하라. 
형상으로 찍으면 (4,)라고 하는 행이 추출된다.


In [74]:
arr2[:, 1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

행은 상관없이 2열과 3열을 출력할 수 있다.
행의 경우도 마찬가지로 특정 행들만 출력할 수 있다.

이때의 형상은?


In [75]:
arr2[:, 1:3].shape

(3, 2)

떨어져 있는 특정 행/열을 동시에 뽑을 수 있을까?
슬라이스로는 떨어져 있는 것을 뽑아낼 수 없다.
따로 따로 뽑기 위해 따로 배열을 만든다? 이렇게 말고 
한방에 어떻게 할까?
인덱싱 컬렉션을 리스트 형태로 넣어서 뽑으면 된다

In [76]:
arr2[:, [1,3]]

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

2열과 4열을 추출해내는 것이다.

In [77]:
temp = [1,3]
arr2[:, temp]

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

이렇게 변수에 리스트를 담아서
딱 그 열만 추출하게 만들 수도 있다
행에 대해서도 이 기능은 적용된다

In [78]:
arr2[[0,2],:]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

이것을 동시에 사용할 수 있을까?
특정 행에서 특정열을 뽑아내는 것이 가능한가?

특정한 행을 지칭하고 열을 고정시켜서 뽑을 수 있다
1차원 배열로 뽑혀나온다

In [79]:
arr2[[0,2],1]

array([ 2, 10])

앞의 행은 떨어져 있는데 열은 슬라이스 줄 수도 있다

In [80]:
arr2[[0,2],1:3]

array([[ 2,  3],
       [10, 11]])

이 경우 2행2열 짜리가 추출되는 것을 볼 수 있다